synt on
set nu
set ai
set si
set hlsearch
set backspace=2
set nocompatible
map <f5> :tabnew
map <f6> gT
map <f7> gt
filetype on
filetype plugin indent on
noremap % v%
set expandtab
set shiftwidth=2
set softtabstop=2
